from django.urls import path

from .views import (
    AssignacioMaterialCreateView,
    BarcodeLookupView,
    AssignacioMaterialListView,
    AssignacioMaterialUpdateView,
    CategoriaMaterialCreateView,
    CategoriaMaterialListView,
    CategoriaMaterialUpdateView,
    CompraMaterialCreateView,
    CompraMaterialListView,
    CompraMaterialUpdateView,
    InventariRapidCreateView,
    ItemMaterialCreateView,
    ItemMaterialDetailView,
    ItemMaterialListView,
    ItemMaterialUpdateView,
    LiniaCompraMaterialCreateView,
    MaterialDashboardView,
    StockMaterialCreateView,
    StockMaterialListView,
    StockMaterialUpdateView,
    TrasllatRapidView,
    UbicacioMaterialCreateView,
    UbicacioMaterialListView,
    UbicacioMaterialUpdateView,
)

urlpatterns = [
    path('', MaterialDashboardView.as_view(), name='dashboard'),
    path('categories/', CategoriaMaterialListView.as_view(), name='categoria_list'),
    path('categories/nova/', CategoriaMaterialCreateView.as_view(), name='categoria_create'),
    path('categories/<int:pk>/editar/', CategoriaMaterialUpdateView.as_view(), name='categoria_update'),
    path('ubicacions/', UbicacioMaterialListView.as_view(), name='ubicacio_list'),
    path('ubicacions/nova/', UbicacioMaterialCreateView.as_view(), name='ubicacio_create'),
    path('ubicacions/<int:pk>/editar/', UbicacioMaterialUpdateView.as_view(), name='ubicacio_update'),
    path('compres/', CompraMaterialListView.as_view(), name='compra_list'),
    path('compres/nova/', CompraMaterialCreateView.as_view(), name='compra_create'),
    path('compres/<int:pk>/editar/', CompraMaterialUpdateView.as_view(), name='compra_update'),
    path('compres/linia/nova/', LiniaCompraMaterialCreateView.as_view(), name='linia_compra_create'),
    path('items/', ItemMaterialListView.as_view(), name='item_list'),
    path('items/nou/', ItemMaterialCreateView.as_view(), name='item_create'),
    path('items/<int:pk>/', ItemMaterialDetailView.as_view(), name='item_detail'),
    path('items/<int:pk>/editar/', ItemMaterialUpdateView.as_view(), name='item_update'),
    path('stocks/', StockMaterialListView.as_view(), name='stock_list'),
    path('stocks/nou/', StockMaterialCreateView.as_view(), name='stock_create'),
    path('stocks/<int:pk>/editar/', StockMaterialUpdateView.as_view(), name='stock_update'),
    path('assignacions/', AssignacioMaterialListView.as_view(), name='assignacio_list'),
    path('assignacions/nova/', AssignacioMaterialCreateView.as_view(), name='assignacio_create'),
    path('assignacions/<int:pk>/editar/', AssignacioMaterialUpdateView.as_view(), name='assignacio_update'),
    path('trasllat-rapid/', TrasllatRapidView.as_view(), name='trasllat_rapid'),
    path('inventari-rapid/', InventariRapidCreateView.as_view(), name='inventari_rapid'),
    path('api/barcode-lookup/', BarcodeLookupView.as_view(), name='barcode_lookup'),
]
