# Generated by Django 5.1.15 on 2026-03-20 15:55

import django.db.models.deletion
from django.db import migrations, models


def seed_agenda_catalogs(apps, schema_editor):
    ActeTipus = apps.get_model("agenda", "ActeTipus")
    SegmentVisibilitat = apps.get_model("agenda", "SegmentVisibilitat")

    tipus_defaults = [
        "Assemblea",
        "Reunió interna",
        "Reunió amb entitat",
        "Acte propi",
        "Acte extern",
        "Paradeta",
    ]
    for ordre, nom in enumerate(tipus_defaults, start=1):
        ActeTipus.objects.get_or_create(nom=nom, defaults={"ordre": ordre, "actiu": True})

    role_segments = [
        ("ADMINISTRADOR", "Administrador"),
        ("COORDINADOR", "Coordinador"),
        ("VOLUNTARI", "Voluntari / militant"),
        ("CONSULTA", "Consulta"),
    ]
    for ordre, (codi, etiqueta) in enumerate(role_segments, start=1):
        SegmentVisibilitat.objects.get_or_create(
            ambit="ROL",
            codi=codi,
            defaults={"etiqueta": etiqueta, "ordre": ordre, "actiu": True},
        )

    user_type_segments = [
        ("MILITANT", "Militant"),
        ("VOLUNTARI", "Voluntari"),
        ("AMIC", "Amic"),
    ]
    for ordre, (codi, etiqueta) in enumerate(user_type_segments, start=1):
        SegmentVisibilitat.objects.get_or_create(
            ambit="TIPUS",
            codi=codi,
            defaults={"etiqueta": etiqueta, "ordre": ordre, "actiu": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_acte_external_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeTipus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color HEX opcional per destacar el tipus.",
                        max_length=7,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actiu", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "tipus d'acte",
                "verbose_name_plural": "tipus d'actes",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AddField(
            model_name="acte",
            name="aforament",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acte",
            name="fi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acte",
            name="punt_trobada",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="acte",
            name="tipus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actes",
                to="agenda.actetipus",
            ),
        ),
        migrations.CreateModel(
            name="SegmentVisibilitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                (
                    "ambit",
                    models.CharField(
                        choices=[("ROL", "Rol"), ("TIPUS", "Tipus d'usuari")],
                        max_length=10,
                    ),
                ),
                ("codi", models.CharField(max_length=50)),
                ("etiqueta", models.CharField(max_length=100)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actiu", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "segment de visibilitat",
                "verbose_name_plural": "segments de visibilitat",
                "ordering": ["ambit", "ordre", "etiqueta"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ambit", "codi"),
                        name="agenda_unique_segment_scope_code",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="acte",
            name="assistencia_permesa_per",
            field=models.ManyToManyField(
                blank=True,
                related_name="actes_assistencia",
                to="agenda.segmentvisibilitat",
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="visible_per",
            field=models.ManyToManyField(
                blank=True,
                related_name="actes_visibles",
                to="agenda.segmentvisibilitat",
            ),
        ),
        migrations.RunPython(seed_agenda_catalogs, migrations.RunPython.noop),
    ]
