# Generated by Django 5.1.15 on 2026-03-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_conditional_external_unique"),
        ("entitats", "0001_initial"),
        ("persones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acte",
            name="entitats_relacionades",
            field=models.ManyToManyField(
                blank=True, related_name="actes_relacionats", to="entitats.entitat"
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="persones_relacionades",
            field=models.ManyToManyField(
                blank=True, related_name="actes_relacionats", to="persones.persona"
            ),
        ),
    ]
