# Generated by Django 5.2.13 on 2026-04-17 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_force_imported_events_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramEventImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("instagram_url", models.URLField()),
                ("text_manual", models.TextField(blank=True)),
                ("text_extret", models.TextField(blank=True)),
                ("observacions", models.TextField(blank=True)),
                (
                    "imatge",
                    models.ImageField(
                        blank=True, null=True, upload_to="agenda/instagram_imports/"
                    ),
                ),
                ("camps_proposats", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "acte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports_instagram",
                        to="agenda.acte",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_event_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "importació d’Instagram",
                "verbose_name_plural": "importacions d’Instagram",
                "ordering": ["-creat_el"],
            },
        ),
    ]
