# Generated by Django 5.2.13 on 2026-04-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0008_instagrameventimport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InstagramEventImport",
        ),
    ]
