# Generated by Django 5.2.13 on 2026-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_delete_instagrameventimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="acte",
            name="imatge",
            field=models.ImageField(blank=True, upload_to="material/agenda/"),
        ),
    ]
