# Generated by Django 5.2.14 on 2026-05-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entitats", "0001_initial"),
        ("persones", "0001_initial"),
        ("reunions", "0006_alter_tipusreunio_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=200)),
                ("descripcio", models.TextField(blank=True, default="")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("EN_REVISIO", "En revisió"),
                            ("DEFINITIU", "Definitiu"),
                            ("A_FER", "Cal fer alguna cosa"),
                        ],
                        default="PENDENT",
                        max_length=20,
                    ),
                ),
                (
                    "creat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocs_programa_creats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pare",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subblocs",
                        to="programaelectoral.blocprograma",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloc del programa",
                "verbose_name_plural": "blocs del programa",
                "ordering": ("ordre", "titol"),
                "permissions": [
                    ("manage_programa_electoral", "Pot gestionar el programa electoral")
                ],
            },
        ),
        migrations.CreateModel(
            name="IdeaPluja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=300)),
                ("descripcio", models.TextField(blank=True, default="")),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("ENTITAT", "Reunió amb entitat"),
                            ("PERSONA_EXTERNA", "Contacte amb persona"),
                            ("REUNIO_INTERNA", "Reunió interna del partit"),
                            ("FORMULARI_PUBLIC", "Formulari públic"),
                            ("XARXES", "Xarxes socials"),
                            ("ALTRA", "Altra font"),
                        ],
                        default="ALTRA",
                        max_length=20,
                    ),
                ),
                (
                    "creat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idees_pluja_creades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "font_entitat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idees_pluja",
                        to="entitats.entitat",
                    ),
                ),
                (
                    "font_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idees_pluja",
                        to="persones.persona",
                    ),
                ),
                (
                    "font_reunio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idees_pluja",
                        to="reunions.reunio",
                    ),
                ),
            ],
            options={
                "verbose_name": "idea de la pluja d'idees",
                "verbose_name_plural": "idees de la pluja d'idees",
                "ordering": ("-creat_el",),
            },
        ),
        migrations.CreateModel(
            name="IdeaPublica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("idea", models.TextField()),
                ("nom", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("telefon", models.CharField(blank=True, default="", max_length=30)),
                ("processada", models.BooleanField(default=False)),
                (
                    "idea_pluja_resultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origen_public",
                        to="programaelectoral.ideapluja",
                    ),
                ),
                (
                    "persona_identificada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idees_publiques",
                        to="persones.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "idea pública",
                "verbose_name_plural": "idees públiques",
                "ordering": ("-creat_el",),
            },
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=300)),
                ("contingut", models.TextField(blank=True, default="")),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("ESBORRANY", "Esborrany"),
                            ("A_REVISAR", "Cal revisar"),
                            ("CONFIRMADA", "Confirmada"),
                            ("DEFINITIVA", "Definitiva"),
                            ("DESCARTADA", "Descartada"),
                        ],
                        default="ESBORRANY",
                        max_length=20,
                    ),
                ),
                (
                    "bloc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propostes",
                        to="programaelectoral.blocprograma",
                    ),
                ),
                (
                    "creat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propostes_creades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proposta",
                "verbose_name_plural": "propostes",
                "ordering": ("bloc__ordre", "bloc__titol", "titol"),
            },
        ),
        migrations.AddField(
            model_name="ideapluja",
            name="proposta_associada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="idees_origen",
                to="programaelectoral.proposta",
            ),
        ),
        migrations.CreateModel(
            name="ComentariProposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comentaris_proposta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentaris",
                        to="programaelectoral.proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "comentari de proposta",
                "verbose_name_plural": "comentaris de proposta",
                "ordering": ("creat_el",),
            },
        ),
    ]
