from django.urls import path

from .views import (
    ActaCreateOrUpdateView,
    ReunioActaExportView,
    ReunioOrdreDiaExportView,
    ActaUpdateView,
    PuntActaCreateView,
    PuntActaTaskCommandCreateView,
    PuntActaTaskQuickCreateView,
    PuntActaQuickUpdateView,
    PuntActaUpdateView,
    PuntOrdreDiaCreateFromTaskView,
    PuntOrdreDiaCreateView,
    PuntOrdreDiaDeleteView,
    PuntOrdreDiaMoveView,
    PuntOrdreDiaUpdateView,
    ReunioCreateView,
    ReunioActaWorkspaceView,
    ReunioDetailView,
    ReunioQuickTaskCreateView,
    ReunioListView,
    ReunioUpdateView,
    SeguimentPanelView,
    SeguimentTascaCreateView,
    TascaCreateView,
    TascaDetailView,
    TascaListView,
    TascaRelacioReunioCreateView,
    TascaUpdateView,
)

urlpatterns = [
    path('', ReunioListView.as_view(), name='reunio_list'),
    path('seguiment/', SeguimentPanelView.as_view(), name='panel_seguiment'),
    path('nova/', ReunioCreateView.as_view(), name='reunio_create'),
    path('<int:pk>/', ReunioDetailView.as_view(), name='reunio_detail'),
    path('<int:pk>/editar/', ReunioUpdateView.as_view(), name='reunio_update'),
    path('<int:pk>/ordre-dia/afegir/', PuntOrdreDiaCreateView.as_view(), name='punt_ordre_create'),
    path('<int:pk>/ordre-dia/exportar/', ReunioOrdreDiaExportView.as_view(), name='ordre_dia_export'),
    path('ordre-dia/<int:pk>/editar/', PuntOrdreDiaUpdateView.as_view(), name='punt_ordre_update'),
    path('<int:pk>/ordre-dia/<int:punt_pk>/eliminar/', PuntOrdreDiaDeleteView.as_view(), name='punt_ordre_delete'),
    path('<int:pk>/ordre-dia/<int:punt_pk>/moure/', PuntOrdreDiaMoveView.as_view(), name='punt_ordre_move'),
    path('<int:pk>/ordre-dia/des-de-tasca/<int:tasca_pk>/', PuntOrdreDiaCreateFromTaskView.as_view(), name='punt_ordre_from_tasca'),
    path('<int:pk>/acta/', ActaCreateOrUpdateView.as_view(), name='acta_upsert'),
    path('<int:pk>/acta/execucio/', ReunioActaWorkspaceView.as_view(), name='acta_workspace'),
    path('<int:pk>/acta/exportar/', ReunioActaExportView.as_view(), name='acta_export'),
    path('acta/<int:pk>/editar/', ActaUpdateView.as_view(), name='acta_update'),
    path('acta/<int:acta_pk>/punts/afegir/', PuntActaCreateView.as_view(), name='punt_acta_create'),
    path('<int:pk>/tasques/rapida/', ReunioQuickTaskCreateView.as_view(), name='tasca_rapida_create'),
    path('punts-acta/<int:pk>/editar/', PuntActaUpdateView.as_view(), name='punt_acta_update'),
    path('punts-acta/<int:pk>/quick-update/', PuntActaQuickUpdateView.as_view(), name='punt_acta_quick_update'),
    path('punts-acta/<int:pk>/tasques/rapida/', PuntActaTaskQuickCreateView.as_view(), name='punt_acta_task_quick_create'),
    path('punts-acta/<int:pk>/tasques/comandes/', PuntActaTaskCommandCreateView.as_view(), name='punt_acta_task_command_create'),
    path('tasques/', TascaListView.as_view(), name='tasca_list'),
    path('tasques/nova/', TascaCreateView.as_view(), name='tasca_create'),
    path('tasques/<int:pk>/', TascaDetailView.as_view(), name='tasca_detail'),
    path('tasques/<int:pk>/editar/', TascaUpdateView.as_view(), name='tasca_update'),
    path('tasques/<int:pk>/seguiments/afegir/', SeguimentTascaCreateView.as_view(), name='seguiment_create'),
    path('tasques/<int:pk>/relacions/afegir/', TascaRelacioReunioCreateView.as_view(), name='tasca_relacio_create'),
]
