# Generated by Django 5.1.15 on 2026-03-23 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entitats", "0001_initial"),
        ("persones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaCampanya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=120, unique=True)),
                ("descripcio", models.TextField(blank=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "àrea de campanya",
                "verbose_name_plural": "àrees de campanya",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="EtiquetaReunioTasques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color HEX opcional per destacar l’etiqueta.",
                        max_length=7,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "etiqueta de reunions i tasques",
                "verbose_name_plural": "etiquetes de reunions i tasques",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Acta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("resum_general", models.TextField(blank=True)),
                ("acords_presos", models.TextField(blank=True)),
                ("observacions", models.TextField(blank=True)),
                ("data_tancament", models.DateField(blank=True, null=True)),
                (
                    "estat",
                    models.CharField(
                        choices=[("ESBORRANY", "Esborrany"), ("VALIDADA", "Validada")],
                        default="ESBORRANY",
                        max_length=20,
                    ),
                ),
                (
                    "redactada_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actes_redactades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "acta",
                "verbose_name_plural": "actes",
                "ordering": ["-reunio__inici"],
            },
        ),
        migrations.CreateModel(
            name="PuntOrdreDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("titol", models.CharField(max_length=255)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "durada_estimada",
                    models.PositiveIntegerField(
                        blank=True, help_text="Durada estimada en minuts.", null=True
                    ),
                ),
                ("requereix_acord", models.BooleanField(default=False)),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("TRACTAT", "Tractat"),
                            ("APLACAT", "Aplaçat"),
                            ("NO_TRACTAT", "No tractat"),
                        ],
                        default="PENDENT",
                        max_length=20,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punts_ordre_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "punt de l'ordre del dia",
                "verbose_name_plural": "punts de l'ordre del dia",
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PuntActa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("titol", models.CharField(max_length=255)),
                ("contingut", models.TextField(blank=True)),
                ("acords", models.TextField(blank=True)),
                ("ve_de_ordre_dia", models.BooleanField(default=False)),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punts",
                        to="reunions.acta",
                    ),
                ),
                (
                    "punt_ordre_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punts_acta_generats",
                        to="reunions.puntordredia",
                    ),
                ),
            ],
            options={
                "verbose_name": "punt d'acta",
                "verbose_name_plural": "punts d'acta",
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Reunio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=255)),
                (
                    "tipus",
                    models.CharField(
                        choices=[
                            ("INTERNA", "Reunió interna"),
                            ("ASSEMBLEA", "Assemblea"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PREPARACIO", "En preparació"),
                            ("CONVOCADA", "Convocada"),
                            ("CELEBRADA", "Celebrada"),
                            ("TANCADA", "Tancada"),
                            ("CANCEL_LADA", "Cancel·lada"),
                        ],
                        default="PREPARACIO",
                        max_length=20,
                    ),
                ),
                ("inici", models.DateTimeField()),
                ("fi", models.DateTimeField(blank=True, null=True)),
                ("ubicacio", models.CharField(blank=True, max_length=255)),
                ("descripcio", models.TextField(blank=True)),
                ("objectiu", models.TextField(blank=True)),
                ("es_estrategica", models.BooleanField(default=False)),
                (
                    "es_interna",
                    models.BooleanField(
                        default=True, help_text="Control simple de visibilitat interna."
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunions",
                        to="reunions.areacampanya",
                    ),
                ),
                (
                    "assistents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reunions_assistides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "convocada_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reunions_convocades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entitats_relacionades",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reunions_relacionades",
                        to="entitats.entitat",
                    ),
                ),
                (
                    "etiquetes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reunions",
                        to="reunions.etiquetareuniotasques",
                    ),
                ),
                (
                    "moderada_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunions_moderades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persones_relacionades",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reunions_relacionades",
                        to="persones.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "reunió",
                "verbose_name_plural": "reunions",
                "ordering": ["-inici", "-creat_el"],
            },
        ),
        migrations.AddField(
            model_name="puntordredia",
            name="reunio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="punts_ordre_dia",
                to="reunions.reunio",
            ),
        ),
        migrations.AddField(
            model_name="acta",
            name="reunio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acta",
                to="reunions.reunio",
            ),
        ),
        migrations.CreateModel(
            name="Tasca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=255)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("EN_CURS", "En curs"),
                            ("BLOQUEJADA", "Bloquejada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCEL_LADA", "Cancel·lada"),
                        ],
                        default="PENDENT",
                        max_length=20,
                    ),
                ),
                (
                    "prioritat",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MITJANA", "Mitjana"),
                            ("ALTA", "Alta"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MITJANA",
                        max_length=20,
                    ),
                ),
                ("data_limit", models.DateField(blank=True, null=True)),
                ("observacions_seguiment", models.TextField(blank=True)),
                ("resultat_tancament", models.TextField(blank=True)),
                ("proposar_seguent_ordre_dia", models.BooleanField(default=False)),
                ("motiu_proposta_ordre_dia", models.TextField(blank=True)),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("PUNT_ACTA", "Punt d’acta"),
                            ("REUNIO", "Reunió"),
                            ("INDEPENDENT", "Independent"),
                        ],
                        default="INDEPENDENT",
                        max_length=20,
                    ),
                ),
                ("es_estrategica", models.BooleanField(default=False)),
                (
                    "visibilitat",
                    models.CharField(
                        choices=[
                            ("INTERNA", "Interna"),
                            ("COORDINACIO", "Només coordinació"),
                        ],
                        default="INTERNA",
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasques",
                        to="reunions.areacampanya",
                    ),
                ),
                (
                    "collaboradors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasques_collaboradors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasques_creades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entitats_relacionades",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasques_relacionades",
                        to="entitats.entitat",
                    ),
                ),
                (
                    "etiquetes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasques",
                        to="reunions.etiquetareuniotasques",
                    ),
                ),
                (
                    "persones_relacionades",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasques_relacionades",
                        to="persones.persona",
                    ),
                ),
                (
                    "punt_acta_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasques_generades",
                        to="reunions.puntacta",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasques_assignades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reunio_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasques_originades",
                        to="reunions.reunio",
                    ),
                ),
            ],
            options={
                "verbose_name": "tasca",
                "verbose_name_plural": "tasques",
                "ordering": ["data_limit", "-es_estrategica", "-creat_el"],
            },
        ),
        migrations.CreateModel(
            name="SeguimentTasca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                (
                    "tipus",
                    models.CharField(
                        choices=[
                            ("COMENTARI", "Comentari"),
                            ("BLOCATGE", "Bloqueig"),
                            ("AVENC", "Avenç"),
                            ("DECISIO", "Decisió"),
                        ],
                        default="COMENTARI",
                        max_length=20,
                    ),
                ),
                ("comentari", models.TextField()),
                (
                    "nou_estat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("EN_CURS", "En curs"),
                            ("BLOQUEJADA", "Bloquejada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCEL_LADA", "Cancel·lada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguiments_tasca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reunio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguiments_tasca",
                        to="reunions.reunio",
                    ),
                ),
                (
                    "tasca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguiments",
                        to="reunions.tasca",
                    ),
                ),
            ],
            options={
                "verbose_name": "seguiment de tasca",
                "verbose_name_plural": "seguiments de tasques",
                "ordering": ["-creat_el"],
            },
        ),
        migrations.CreateModel(
            name="HistoricEstatTasca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                (
                    "estat_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("EN_CURS", "En curs"),
                            ("BLOQUEJADA", "Bloquejada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCEL_LADA", "Cancel·lada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estat_nou",
                    models.CharField(
                        choices=[
                            ("PENDENT", "Pendent"),
                            ("EN_CURS", "En curs"),
                            ("BLOQUEJADA", "Bloquejada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCEL_LADA", "Cancel·lada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motiu", models.TextField(blank=True)),
                (
                    "canviat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canvis_estat_tasca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historic_estats",
                        to="reunions.tasca",
                    ),
                ),
            ],
            options={
                "verbose_name": "històric d’estat de tasca",
                "verbose_name_plural": "històrics d’estat de tasca",
                "ordering": ["-creat_el"],
            },
        ),
        migrations.CreateModel(
            name="TascaRelacioReunio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                (
                    "tipus_relacio",
                    models.CharField(
                        choices=[
                            ("ORIGEN", "Origen"),
                            ("SEGUIMENT", "Seguiment"),
                            ("PROPOSTA_ORDRE_DIA", "Proposta per ordre del dia"),
                            ("TANCAMENT", "Tancament"),
                        ],
                        default="SEGUIMENT",
                        max_length=20,
                    ),
                ),
                ("resum", models.TextField(blank=True)),
                (
                    "tractada_el",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "punt_acta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relacions_tasca",
                        to="reunions.puntacta",
                    ),
                ),
                (
                    "punt_ordre_dia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relacions_tasca",
                        to="reunions.puntordredia",
                    ),
                ),
                (
                    "reunio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relacions_tasca",
                        to="reunions.reunio",
                    ),
                ),
                (
                    "tasca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relacions_reunio",
                        to="reunions.tasca",
                    ),
                ),
            ],
            options={
                "verbose_name": "relació entre tasca i reunió",
                "verbose_name_plural": "relacions entre tasques i reunions",
                "ordering": ["-tractada_el", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="puntacta",
            constraint=models.UniqueConstraint(
                fields=("acta", "ordre"), name="reunions_unique_punt_acta_per_acta"
            ),
        ),
        migrations.AddConstraint(
            model_name="puntordredia",
            constraint=models.UniqueConstraint(
                fields=("reunio", "ordre"), name="reunions_unique_punt_ordre_per_reunio"
            ),
        ),
        migrations.AddConstraint(
            model_name="tascarelacioreunio",
            constraint=models.UniqueConstraint(
                fields=(
                    "tasca",
                    "reunio",
                    "punt_ordre_dia",
                    "punt_acta",
                    "tipus_relacio",
                ),
                name="reunions_unique_tasca_reunio_link",
            ),
        ),
    ]
