# Generated by Django 5.2.13 on 2026-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reunions", "0002_reunio_acte_agenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="acta",
            name="incidencies_post_acte",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="acta",
            name="resultat_post_acte",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="acta",
            name="tasques_derivades_post_acte",
            field=models.TextField(blank=True),
        ),
    ]
