# Generated by Django 5.2.13 on 2026-04-13 07:56

import django.db.models.deletion
import reunions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reunions",
            "0003_acta_incidencies_post_acte_acta_resultat_post_acte_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAdjunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("titol", models.CharField(max_length=255)),
                ("descripcio", models.TextField(blank=True)),
                (
                    "arxiu",
                    models.FileField(upload_to=reunions.models._reunions_document_path),
                ),
                (
                    "pujat_per",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_reunions_pujats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reunio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_adjunts",
                        to="reunions.reunio",
                    ),
                ),
                (
                    "tasca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_adjunts",
                        to="reunions.tasca",
                    ),
                ),
            ],
            options={
                "verbose_name": "document adjunt",
                "verbose_name_plural": "documents adjunts",
                "ordering": ["-creat_el"],
            },
        ),
    ]
