# Generated by Django 5.2.13 on 2026-04-16 09:39

import django.db.models.deletion
from django.db import migrations, models


def seed_tipus_reunio(apps, schema_editor):
    TipusReunio = apps.get_model('reunions', 'TipusReunio')
    defaults = [
        ('interna', 'Reunió interna', 0, True),
        ('assemblea', 'Assemblea', 10, True),
        ('amb_persona', 'Reunió amb persona', 20, False),
        ('amb_entitat', 'Reunió amb entitat', 30, False),
    ]
    for codi, nom, ordre, permet_acta in defaults:
        TipusReunio.objects.update_or_create(
            codi=codi,
            defaults={
                'nom': nom,
                'ordre': ordre,
                'activa': True,
                'permet_ordre_dia_i_acta': permet_acta,
            },
        )


def migrate_reunio_tipus_to_fk(apps, schema_editor):
    Reunio = apps.get_model('reunions', 'Reunio')
    TipusReunio = apps.get_model('reunions', 'TipusReunio')

    legacy_to_code = {
        'INTERNA': 'interna',
        'ASSEMBLEA': 'assemblea',
    }
    fallback_type = TipusReunio.objects.get(codi='interna')
    for reunio in Reunio.objects.all().only('id', 'tipus'):
        code = legacy_to_code.get(reunio.tipus, 'interna')
        tipus = TipusReunio.objects.filter(codi=code).first() or fallback_type
        reunio.tipus_nou_id = tipus.id
        reunio.save(update_fields=['tipus_nou'])


class Migration(migrations.Migration):

    dependencies = [
        ('reunions', '0004_documentadjunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipusReunio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('codi', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('descripcio', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('permet_ordre_dia_i_acta', models.BooleanField(default=True, help_text='Si es desactiva, la reunió es considera informal i no requereix ordre del dia ni acta.')),
            ],
            options={
                'verbose_name': 'tipus de reunió',
                'verbose_name_plural': 'tipus de reunió',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.RunPython(seed_tipus_reunio, migrations.RunPython.noop),
        migrations.AddField(
            model_name='reunio',
            name='tipus_nou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reunions.tipusreunio'),
        ),
        migrations.RunPython(migrate_reunio_tipus_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(model_name='reunio', name='tipus'),
        migrations.RenameField(model_name='reunio', old_name='tipus_nou', new_name='tipus'),
        migrations.AlterField(
            model_name='reunio',
            name='tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reunions', to='reunions.tipusreunio'),
        ),
    ]
