# Generated by Django 5.2.14 on 2026-05-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reunions", "0005_tipusreunio_alter_reunio_tipus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipusreunio",
            options={
                "ordering": ["ordre", "nom"],
                "verbose_name": "tipus de reunió",
                "verbose_name_plural": "tipus de reunions",
            },
        ),
    ]
