# Generated by Django 5.2 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0007_force_imported_events_published'),
        ('entitats', '0001_initial'),
        ('reunions', '0004_documentadjunt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('pare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fills', to='material.categoriamaterial')),
            ],
            options={'ordering': ['nom'], 'verbose_name': 'categoria de material', 'verbose_name_plural': 'categories de material'},
        ),
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('data_compra', models.DateField()),
                ('proveidor', models.CharField(max_length=150)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pagament', models.CharField(choices=[('EFECTIU', 'Efectiu'), ('TARGETA', 'Targeta'), ('TRANSFERENCIA', 'Transferència'), ('BIZUM', 'Bizum'), ('ALTRE', 'Altre')], default='TARGETA', max_length=20)),
                ('num_factura_ticket', models.CharField(blank=True, max_length=80)),
                ('document', models.FileField(blank=True, upload_to='material/compres/')),
                ('observacions', models.TextField(blank=True)),
                ('pagador_entitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compres_material_pagades', to='entitats.entitat')),
                ('pagador_usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compres_material_pagades', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-data_compra', '-id'], 'verbose_name': 'compra de material', 'verbose_name_plural': 'compres de material'},
        ),
        migrations.CreateModel(
            name='UbicacioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adreca', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('responsable_per_defecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicacions_material_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['nom'], 'verbose_name': 'ubicació de material', 'verbose_name_plural': 'ubicacions de material'},
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('codi_intern', models.CharField(db_index=True, max_length=40, unique=True)),
                ('descripcio', models.CharField(max_length=255)),
                ('estat', models.CharField(choices=[('OPERATIU', 'Operatiu'), ('REPARACIO', 'En reparació'), ('BAIXA', 'Baixa')], default='OPERATIU', max_length=20)),
                ('data_alta', models.DateField()),
                ('valor_estimad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codi_barres', models.CharField(blank=True, db_index=True, max_length=64)),
                ('foto_principal', models.ImageField(blank=True, upload_to='material/items/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.categoriamaterial')),
                ('ubicacio_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='material.ubicaciomaterial')),
            ],
            options={'ordering': ['codi_intern'], 'verbose_name': 'ítem de material', 'verbose_name_plural': 'ítems de material'},
        ),
        migrations.CreateModel(
            name='LiniaCompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(max_length=255)),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_percent', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('total_linia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codi_barres', models.CharField(blank=True, db_index=True, max_length=64)),
                ('foto', models.ImageField(blank=True, upload_to='material/linies/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.categoriamaterial')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='material.compramaterial')),
            ],
            options={'ordering': ['compra_id', 'id'], 'verbose_name': 'línia de compra de material', 'verbose_name_plural': 'línies de compra de material'},
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('producte', models.CharField(max_length=200)),
                ('quantitat_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unitat', models.CharField(default='u', max_length=20)),
                ('llindar_minim', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codi_barres', models.CharField(blank=True, db_index=True, max_length=64)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.categoriamaterial')),
                ('ubicacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='material.ubicaciomaterial')),
            ],
            options={'ordering': ['producte'], 'verbose_name': 'stock de material', 'verbose_name_plural': 'stocks de material', 'unique_together': {('producte', 'ubicacio')}},
        ),
        migrations.CreateModel(
            name='MovimentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('tipus_moviment', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SORTIDA', 'Sortida'), ('TRASLLAT', 'Trasllat'), ('AJUST', 'Ajust'), ('PRESTEC', 'Préstec'), ('DEVOLUCIO', 'Devolució'), ('BAIXA', 'Baixa')], max_length=20)),
                ('data_moviment', models.DateTimeField(auto_now_add=True)),
                ('quantitat', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('observacions', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviments_material', to=settings.AUTH_USER_MODEL)),
                ('desti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviments_entrada', to='material.ubicaciomaterial')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviments', to='material.itemmaterial')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviments_sortida', to='material.ubicaciomaterial')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviments', to='material.stockmaterial')),
            ],
            options={'ordering': ['-data_moviment'], 'verbose_name': 'moviment de material', 'verbose_name_plural': 'moviments de material'},
        ),
        migrations.CreateModel(
            name='AssignacioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('quantitat_reservada', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('quantitat_retornada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estat_reserva', models.CharField(choices=[('RESERVAT', 'Reservat'), ('PREPARAT', 'Preparat'), ('RETORNAT', 'Retornat')], default='RESERVAT', max_length=20)),
                ('acte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignacions_material', to='agenda.acte')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignacions', to='material.itemmaterial')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignacions', to='material.stockmaterial')),
                ('tasca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignacions_material', to='reunions.tasca')),
            ],
            options={'ordering': ['-creat_el'], 'verbose_name': 'assignació de material', 'verbose_name_plural': 'assignacions de material'},
        ),
    ]
