# Generated by Django 5.2.13 on 2026-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liniacompramaterial",
            name="tipus_linia",
            field=models.CharField(
                choices=[
                    ("INVENTARIABLE", "Inventariable"),
                    ("CONSUMIBLE", "Consumible"),
                ],
                default="CONSUMIBLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockmaterial",
            name="tipus_stock",
            field=models.CharField(
                choices=[
                    ("INVENTARIABLE", "Inventariable"),
                    ("CONSUMIBLE", "Consumible"),
                ],
                default="CONSUMIBLE",
                max_length=20,
            ),
        ),
    ]
