# Generated by Django 5.2.13 on 2026-04-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0002_liniacompramaterial_tipus_linia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmaterial",
            name="tipus_stock",
        ),
    ]
