# Generated by Django 5.2.13 on 2026-04-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0003_remove_stockmaterial_tipus_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmaterial",
            name="linia_compra",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_generat",
                to="material.liniacompramaterial",
            ),
        ),
        migrations.AddField(
            model_name="itemmaterial",
            name="quantitat_actual",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="stockmaterial",
            name="foto_principal",
            field=models.ImageField(blank=True, upload_to="material/stocks/"),
        ),
        migrations.AddField(
            model_name="stockmaterial",
            name="linia_compra",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generat",
                to="material.liniacompramaterial",
            ),
        ),
    ]
