# Generated by Django 5.1.15 on 2026-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuaris", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuari",
            name="tipus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MILITANT", "Militant"),
                    ("VOLUNTARI", "Voluntari"),
                    ("AMIC", "Amic"),
                ],
                default="",
                help_text="Classificació interna per distingir militants, voluntaris i amics.",
                max_length=20,
            ),
        ),
    ]
