# Generated by Django 5.1.15 on 2026-03-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=50)),
                ("web", models.URLField(blank=True)),
                ("tipologia", models.CharField(blank=True, max_length=255)),
                ("ambit", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("external_source", models.CharField(blank=True, max_length=50)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("source_checksum", models.CharField(blank=True, max_length=64)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                (
                    "persones",
                    models.ManyToManyField(
                        blank=True, related_name="entitats", to="persones.persona"
                    ),
                ),
            ],
            options={
                "verbose_name": "entitat",
                "verbose_name_plural": "entitats",
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("external_source__gt", ""), ("external_id__gt", "")
                        ),
                        fields=("external_source", "external_id"),
                        name="entitats_unique_external_source_id",
                    )
                ],
            },
        ),
    ]
