# Generated by Django 5.2.13 on 2026-04-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(default="Municipals 2027", max_length=120)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "candidatura",
                "verbose_name_plural": "candidatures",
                "permissions": [
                    ("manage_electoral_list", "Pot gestionar la llista electoral")
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrantLlista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                (
                    "afiliacio",
                    models.CharField(
                        choices=[
                            ("INDEPENDENT", "Independent"),
                            ("JOVENT", "Jovent"),
                            ("ESQUERRA", "Esquerra"),
                        ],
                        default="ESQUERRA",
                        max_length=20,
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("CONFIRMADA", "Confirmada"),
                            ("PENDENT", "Pendent de confirmació"),
                            ("IDEA", "Idea"),
                        ],
                        default="IDEA",
                        max_length=20,
                    ),
                ),
                (
                    "candidatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrants",
                        to="llistaelectoral.candidatura",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidatures",
                        to="persones.persona",
                    ),
                ),
                (
                    "usuari",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "integrant de llista",
                "verbose_name_plural": "integrants de llista",
                "unique_together": {("candidatura", "persona", "usuari")},
            },
        ),
        migrations.CreateModel(
            name="PosicioLlista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                ("actualitzat_el", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "candidatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posicions",
                        to="llistaelectoral.candidatura",
                    ),
                ),
                (
                    "integrant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posicio",
                        to="llistaelectoral.integrantllista",
                    ),
                ),
            ],
            options={
                "verbose_name": "posició de llista",
                "verbose_name_plural": "posicions de llista",
                "ordering": ("numero",),
                "unique_together": {("candidatura", "numero")},
            },
        ),
    ]
