# Generated by Django 5.2.13 on 2026-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llistaelectoral", "0002_permisllistaelectoral"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrantllista",
            name="observacions",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
    ]
